"""
maxwell.verification.verifier — Verify Python implementations against original equations.

Compares equations extracted from JSON sources against Python implementations
using SymPy symbolic matching and numerical evaluation.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class VerificationResult:
    """Result of verifying one equation against its Python implementation."""

    article_number: int
    equation_latex: str
    python_function: str
    python_file: str

    status: str = "pending"
    """verified, mismatch, unverified, error"""

    confidence: float = 0.0
    """0.0-1.0 confidence that the Python code matches the original equation."""

    details: str = ""
    """Explanation of the verification result."""

    latex_normalized: str = ""
    """Normalized form of the LaTeX equation."""

    code_equivalent: str = ""
    """The equation as found in the Python code."""


class EquationVerifier:
    """Verify that Python implementations match Maxwell's original equations."""

    def __init__(self):
        self._results: list[VerificationResult] = []

    def verify_module(self, py_file: Path, registry) -> list[VerificationResult]:
        """
        Verify all equations cited in a Python module against the registry.

        Args:
            py_file: Path to the Python module
            registry: EquationRegistry instance with extracted equations

        Returns:
            List of VerificationResult for each equation
        """
        results = []
        source = py_file.read_text(encoding="utf-8")

        # Extract cited articles
        cited = self._extract_cited_articles(source)

        for art_num in cited:
            equations = registry.get_equations(art_num)
            for eq in equations:
                # Find the function that cites this article
                func_name = self._find_function_for_article(source, art_num)
                if not func_name:
                    continue

                # Get the function source
                func_source = self._extract_function_source(source, func_name)

                # Perform verification
                result = self._verify_equation(eq, func_name, str(py_file), func_source)
                results.append(result)

        self._results.extend(results)
        return results

    def verify_all_modules(
        self, module_dir: Path, registry
    ) -> list[VerificationResult]:
        """Verify all Python modules in a directory tree."""
        all_results = []
        for py_file in sorted(Path(module_dir).rglob("*.py")):
            if py_file.name.startswith("test_") or py_file.name == "__init__.py":
                continue
            if "verification" in str(py_file):
                continue

            print(f"  Verifying {py_file.relative_to(module_dir)}...")
            results = self.verify_module(py_file, registry)
            all_results.extend(results)

            for r in results:
                status_icon = {
                    "verified": "[OK]",
                    "mismatch": "[!!]",
                    "unverified": "[??]",
                    "error": "[ER]",
                }
                icon = status_icon.get(r.status, "??")
                print(
                    f"    {icon} Art.{r.article_number}: {r.python_function} -- {r.status} ({r.confidence:.0%})"
                )

        return all_results

    def generate_report(self, output_path: Path | str | None = None) -> str:
        """Generate a markdown verification report."""
        lines = []
        lines.append("# Equation Verification Report")
        lines.append("")
        lines.append("> **Generated by:** maxwell.verification.verifier")
        lines.append("")

        # Summary
        total = len(self._results)
        verified = sum(1 for r in self._results if r.status == "verified")
        mismatch = sum(1 for r in self._results if r.status == "mismatch")
        unverified = sum(1 for r in self._results if r.status == "unverified")
        errors = sum(1 for r in self._results if r.status == "error")

        lines.append("## Summary")
        lines.append("")
        lines.append(f"| Status | Count |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Verified | {verified} |")
        lines.append(f"| Mismatch | {mismatch} |")
        lines.append(f"| Unverified | {unverified} |")
        lines.append(f"| Error | {errors} |")
        lines.append(f"| **Total** | **{total}** |")
        lines.append("")

        if verified + mismatch > 0:
            trust_score = (
                verified / (verified + mismatch) if (verified + mismatch) > 0 else 0
            )
            lines.append(
                f"**Trust Score:** {trust_score:.0%} ({verified}/{verified + mismatch} verified)"
            )
            lines.append("")

        # Details by file
        by_file = {}
        for r in self._results:
            if r.python_file not in by_file:
                by_file[r.python_file] = []
            by_file[r.python_file].append(r)

        lines.append("## Per-File Results")
        lines.append("")

        for filepath, results in sorted(by_file.items()):
            lines.append(f"### `{filepath}`")
            lines.append("")
            for r in results:
                status_icon = {
                    "verified": "[OK]",
                    "mismatch": "[!!]",
                    "unverified": "[??]",
                    "error": "[ER]",
                }
                icon = status_icon.get(r.status, "?")
                lines.append(
                    f"- {icon} **Art.{r.article_number}** `{r.python_function}`: {r.status}"
                )
                lines.append(f"  - LaTeX: `{r.equation_latex[:100]}`")
                if r.details:
                    lines.append(f"  - {r.details}")
            lines.append("")

        # Mismatches section
        mismatches = [r for r in self._results if r.status == "mismatch"]
        if mismatches:
            lines.append("## Mismatches Requiring Attention")
            lines.append("")
            for r in mismatches:
                lines.append(f"### Art.{r.article_number} — `{r.python_function}`")
                lines.append(f"- **Original:** `{r.equation_latex}`")
                lines.append(f"- **Code:** `{r.code_equivalent}`")
                lines.append(f"- **Issue:** {r.details}")
                lines.append("")

        report = "\n".join(lines)

        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text(report, encoding="utf-8")
            print(f"\n  Report saved to {output_path}")

        return report

    # ── Private methods ──────────────────────────────────────────

    def _verify_equation(
        self, eq, func_name: str, py_file: str, func_source: str
    ) -> VerificationResult:
        """Verify a single equation against its Python implementation."""
        result = VerificationResult(
            article_number=eq.article_number or 0,
            equation_latex=eq.latex,
            python_function=func_name,
            python_file=py_file,
        )

        try:
            # Try symbolic verification with SymPy
            result = self._sympy_verify(eq, func_source, result)
        except ImportError:
            # SymPy not available, fall back to structural verification
            result = self._structural_verify(eq, func_source, result)
        except Exception as e:
            result.status = "error"
            result.details = f"Verification error: {e}"

        return result

    def _sympy_verify(
        self, eq, func_source: str, result: VerificationResult
    ) -> VerificationResult:
        """Verify using SymPy symbolic comparison."""
        try:
            from sympy import Eq, latex, symbols, sympify
            from sympy.parsing.latex import parse_latex

            # Try to parse the LaTeX equation
            try:
                sympy_expr = parse_latex(eq.latex)
                result.latex_normalized = latex(sympy_expr)
            except Exception:
                # LaTeX parsing failed, try structural
                return self._structural_verify(eq, func_source, result)

            # Check if the function source contains equivalent math
            # Look for numeric evaluation matches
            # This is a heuristic: if the function computes the same formula structure
            if self._structural_match(eq.latex, func_source):
                result.status = "verified"
                result.confidence = 0.85
                result.details = "Structural match confirmed"
            else:
                result.status = "unverified"
                result.confidence = 0.3
                result.details = "SymPy parsed but structural match inconclusive"

        except Exception as e:
            result.status = "error"
            result.details = f"SymPy verification failed: {e}"

        return result

    def _structural_verify(
        self, eq, func_source: str, result: VerificationResult
    ) -> VerificationResult:
        """Verify using structural/heuristic matching."""
        if self._structural_match(eq.latex, func_source):
            result.status = "verified"
            result.confidence = 0.7
            result.details = "Structural/heuristic match"
        else:
            result.status = "unverified"
            result.confidence = 0.2
            result.details = "No clear structural match found in code"

        return result

    def _structural_match(self, latex_eq: str, func_source: str) -> bool:
        """
        Check if the function source code structurally implements the LaTeX equation.

        This is a heuristic check: it looks for key mathematical patterns
        from the LaTeX equation in the Python code.
        """
        # Extract key mathematical tokens from LaTeX
        tokens = self._extract_math_tokens(latex_eq)

        # Check how many tokens appear in the function source
        matches = 0
        for token in tokens:
            if token in func_source:
                matches += 1

        # If more than 60% of tokens match, consider it a structural match
        if len(tokens) > 0:
            return matches / len(tokens) >= 0.6

        return False

    def _extract_math_tokens(self, latex: str) -> list[str]:
        """Extract meaningful mathematical tokens from LaTeX."""
        tokens = []

        # Variable names
        tokens.extend(re.findall(r"\\?[a-zA-Z]+", latex))

        # Numbers
        tokens.extend(re.findall(r"\d+\.?\d*", latex))

        # Operators
        tokens.extend(re.findall(r"[+=\-\*/^]", latex))

        # Greek letters
        tokens.extend(re.findall(r"\\[a-z]{3,}", latex))

        # Function names
        tokens.extend(
            re.findall(r"\\(?:frac|sqrt|int|sum|prod|partial|nabla|left|right)", latex)
        )

        return list(set(tokens))

    def _extract_cited_articles(self, source: str) -> list[int]:
        """Extract article numbers from @maxwell_cite decorators."""
        import ast

        articles = set()
        try:
            tree = ast.parse(source)
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    for decorator in node.decorator_list:
                        if isinstance(decorator, ast.Call):
                            # Get positional args (article numbers)
                            for arg in decorator.args:
                                if isinstance(arg, ast.Constant) and isinstance(
                                    arg.value, int
                                ):
                                    articles.add(arg.value)
                            # Also check for articles= keyword (list form)
                            for kw in decorator.keywords:
                                if kw.arg == "articles":
                                    if isinstance(kw.value, ast.List):
                                        for elt in kw.value.elts:
                                            if isinstance(
                                                elt, ast.Constant
                                            ) and isinstance(elt.value, int):
                                                articles.add(elt.value)
        except SyntaxError:
            pass
        return sorted(articles)

    def _find_function_for_article(
        self, source: str, article_number: int
    ) -> Optional[str]:
        """Find the function name that cites a specific article."""
        import ast

        try:
            tree = ast.parse(source)
            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    for decorator in node.decorator_list:
                        if isinstance(decorator, ast.Call):
                            # Check positional args (article numbers)
                            for arg in decorator.args:
                                if (
                                    isinstance(arg, ast.Constant)
                                    and isinstance(arg.value, int)
                                    and arg.value == article_number
                                ):
                                    return node.name
                            # Also check articles= keyword
                            for kw in decorator.keywords:
                                if kw.arg == "articles":
                                    if isinstance(kw.value, ast.List):
                                        for elt in kw.value.elts:
                                            if (
                                                isinstance(elt, ast.Constant)
                                                and isinstance(elt.value, int)
                                                and elt.value == article_number
                                            ):
                                                return node.name
        except SyntaxError:
            pass
        return None

    def _extract_function_source(self, source: str, func_name: str) -> str:
        """Extract the source code of a specific function."""
        import ast

        try:
            tree = ast.parse(source)
            for node in ast.walk(tree):
                if (
                    isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and node.name == func_name
                ):
                    lines = source.split("\n")
                    # AST uses 0-based line numbers
                    start = node.lineno - 1
                    end = node.end_lineno
                    return "\n".join(lines[start:end])
        except (SyntaxError, AttributeError):
            pass
        return ""
