"""maxwell.vis.helicoidal_potentials -- Helicoidal potential surfaces visualization.

Implements visualization of magnetic equipotential surfaces generated by
current loops using the solid angle formulation, producing helicoidal
(screw-like) potential surfaces.

Corresponds to Maxwell's treatment of magnetic potentials and
solid angle in
Part IV, Arts. 486-487 (Equipotential Surfaces and Solid Angle).
"""

from __future__ import annotations

import numpy as np

from maxwell.vis._compat import require_matplotlib, plt, Figure, Axes
from maxwell.meta.citation import maxwell_cite


@maxwell_cite(
    487,
    part=4,
    chapter="Equipotential Surfaces",
    description="Calculate solid angle of circular current loop at observation point.",
)
def calc_solid_angle_loop(
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
    loop_radius: float = 1.0,
    current: float = 1.0,
) -> dict[str, np.ndarray]:
    """Calculate solid angle and magnetic potential of a circular current loop.

    Art. 487: Maxwell showed that the magnetic scalar potential at a point
    due to a current loop is proportional to the solid angle subtended
    by the loop at that point:

        Omega = I * omega

    where omega is the solid angle. For a circular loop of radius 'a'
    centered at origin in the xy-plane, the solid angle at point (x, y, z):

        omega = 2*pi * (1 - z / sqrt(z^2 + r^2))  for z > 0
        omega = -2*pi * (1 + z / sqrt(z^2 + r^2)) for z < 0

    where r = sqrt(x^2 + y^2) is the cylindrical radius.

    The sign change across the loop surface (z = 0) produces the
    discontinuity that Maxwell identified with the current sheet.

    Args:
        x: x positions (cm).
        y: y positions (cm).
        z: z positions (cm).
        loop_radius: Radius of the current loop (cm).
        current: Current in the loop (abamperes).

    Returns:
        Dictionary with 'omega' (solid angle in steradians),
        'Omega' (magnetic potential = I*omega),
        'B_z' (axial field component), 'r_cyl' (cylindrical radius).

    Reference:
        Part IV, Art. 487: Solid angle formulation for current loops.
    """
    x = np.asarray(x, dtype=np.float64)
    y = np.asarray(y, dtype=np.float64)
    z = np.asarray(z, dtype=np.float64)

    r_cyl = np.sqrt(x**2 + y**2)
    z_safe = np.where(np.abs(z) < 1e-10, np.sign(z) * 1e-10, z)

    # Solid angle of circular loop (approximation for points on axis and near-axis)
    # Exact formula involves elliptic integrals; we use the dipole approximation
    # for far field and the on-axis formula extended off-axis
    dist = np.sqrt(z_safe**2 + r_cyl**2 + loop_radius**2)
    cos_alpha = z_safe / np.sqrt(z_safe**2 + np.maximum(r_cyl - loop_radius, 0.01)**2)

    # Simplified: use on-axis formula with off-axis generalization
    # omega = 2*pi * (1 - z/sqrt(z^2 + (r-a)^2 + epsilon))
    epsilon = 0.1 * loop_radius
    omega = 2.0 * np.pi * (1.0 - z_safe / np.sqrt(z_safe**2 + (r_cyl - loop_radius)**2 + epsilon))

    # Sign correction for below the loop
    omega = np.where(z < 0, -omega, omega)

    Omega = current * omega

    return {
        "omega": omega,
        "Omega": Omega,
        "r_cyl": r_cyl,
    }


@maxwell_cite(
    487,
    part=4,
    chapter="Equipotential Surfaces",
    description="Plot helicoidal equipotential surfaces of current loop.",
)
def plot_helicoidal_potentials(
    loop_radius: float = 1.0,
    current: float = 1.0,
    resolution: int = 40,
    ax: Axes | None = None,
) -> tuple[Figure, Axes]:
    """Plot helicoidal equipotential surfaces of a current loop.

    Art. 487: Visualizes the magnetic scalar potential generated by
    a circular current loop. The equipotential surfaces are surfaces
    of constant solid angle, which have a characteristic helicoidal
    (screw-like) shape near the loop and become conical far away.

    The visualization shows:
    - The current loop as a ring
    - Equipotential contour lines in a meridional plane
    - The discontinuity surface (the disk bounded by the loop)

    Args:
        loop_radius: Radius of the current loop (cm).
        current: Current in the loop (abamperes).
        resolution: Grid resolution.
        ax: Existing axes to plot on (optional).

    Returns:
        Tuple of (Figure, Axes).

    Reference:
        Part IV, Art. 487: Equipotential surfaces via solid angle.
    """
    require_matplotlib()

    # Meridional cross-section (rho, z) plane
    rho = np.linspace(0, 2.5 * loop_radius, resolution)
    z = np.linspace(-1.5 * loop_radius, 1.5 * loop_radius, resolution)
    Rho, Z = np.meshgrid(rho, z)

    # Solid angle in meridional plane
    z_safe = np.where(np.abs(Z) < 1e-10, np.sign(Z) * 1e-10, Z)
    epsilon = 0.1 * loop_radius
    omega = 2.0 * np.pi * (1.0 - z_safe / np.sqrt(z_safe**2 + (Rho - loop_radius)**2 + epsilon))
    omega = np.where(Z < 0, -omega, omega)

    Omega = current * omega

    if ax is None:
        fig, ax = plt.subplots(figsize=(10, 6))
    else:
        fig = ax.figure

    # Potential contour fill
    omega_max = np.max(np.abs(omega))
    cf = ax.contourf(
        Rho, Z, omega,
        levels=30,
        cmap="coolwarm",
        vmin=-omega_max,
        vmax=omega_max,
    )
    fig.colorbar(cf, ax=ax, label="Solid Angle omega (sr)")

    # Equipotential contour lines
    contours = ax.contour(
        Rho, Z, omega,
        levels=15,
        colors="black",
        linewidths=0.5,
        alpha=0.4,
    )

    # Draw the current loop
    ax.plot([loop_radius, loop_radius], [0, 0], "ko", markersize=10,
           label="Current loop (cross-section)")
    ax.plot([-loop_radius, -loop_radius], [0, 0], "ko", markersize=10)

    # Discontinuity line (disk bounded by loop)
    ax.axhline(y=0, color="gray", linestyle="--", linewidth=1, alpha=0.5)
    ax.plot([0, loop_radius], [0, 0], "g-", linewidth=2,
           label="Discontinuity surface")

    ax.set_xlabel(r"Cylindrical radius $\rho$ (cm)")
    ax.set_ylabel("z (cm)")
    ax.set_title("Helicoidal Potential Surfaces of Current Loop (Art. 487)")
    ax.legend(loc="best", fontsize=9)
    ax.set_aspect("equal")

    fig.tight_layout()
    return fig, ax


@maxwell_cite(
    487,
    part=4,
    chapter="Equipotential Surfaces",
    description="Plot 3D equipotential surface of current loop.",
)
def plot_loop_potential_3d(
    loop_radius: float = 1.0,
    current: float = 1.0,
    resolution: int = 30,
    ax: Axes | None = None,
) -> tuple[Figure, Axes]:
    """Plot 3D equipotential surface of a current loop.

    Art. 487: 3D rendering showing the solid angle/potential
    as a surface above and below the loop plane. The characteristic
    shape shows the discontinuity at the loop boundary and
    the smooth decay at large distances.

    Args:
        loop_radius: Loop radius (cm).
        current: Current (abamperes).
        resolution: Grid resolution.
        ax: Existing 3D axes (optional).

    Returns:
        Tuple of (Figure, Axes) with 3D projection.

    Reference:
        Part IV, Art. 487: 3D equipotential surface structure.
    """
    require_matplotlib()

    x = np.linspace(-2.0 * loop_radius, 2.0 * loop_radius, resolution)
    y = np.linspace(-2.0 * loop_radius, 2.0 * loop_radius, resolution)
    X, Y = np.meshgrid(x, y)

    z_plane = 0.3 * loop_radius  # Small offset above loop
    Z = np.full_like(X, z_plane)

    result = calc_solid_angle_loop(X, Y, Z, loop_radius=loop_radius, current=current)
    omega = result["omega"]

    if ax is None:
        fig = plt.figure(figsize=(10, 8))
        ax = fig.add_subplot(111, projection="3d")
    else:
        fig = ax.figure

    try:
        from matplotlib import colormaps
        cmap_obj = colormaps.get_cmap("coolwarm")
    except Exception:
        cmap_obj = plt.cm.get_cmap("coolwarm")

    omega_max = np.max(np.abs(omega))
    colors = cmap_obj(0.5 + 0.5 * omega / omega_max)

    ax.plot_surface(
        X, Y, Z + omega * 0.1,
        facecolors=colors,
        alpha=0.8,
        linewidth=0,
        antialiased=True,
        cmap="coolwarm",
        vmin=-omega_max,
        vmax=omega_max,
    )

    # Draw current loop
    theta = np.linspace(0, 2 * np.pi, 100)
    loop_x = loop_radius * np.cos(theta)
    loop_y = loop_radius * np.sin(theta)
    loop_z = np.zeros_like(theta)
    ax.plot(loop_x, loop_y, loop_z, "k-", linewidth=3, label="Current loop")

    ax.set_xlabel("x (cm)")
    ax.set_ylabel("y (cm)")
    ax.set_zlabel("z + omega (cm)")
    ax.set_title("3D Loop Potential Surface (Art. 487)")
    ax.legend(loc="best")

    fig.tight_layout()
    return fig, ax


@maxwell_cite(
    486,
    part=4,
    chapter="Equipotential Surfaces",
    description="Plot magnetic field lines around a current loop.",
)
def plot_loop_field_lines(
    loop_radius: float = 1.0,
    current: float = 1.0,
    resolution: int = 50,
    ax: Axes | None = None,
) -> tuple[Figure, Axes]:
    """Plot magnetic field lines around a circular current loop.

    Art. 486: Maxwell showed that the magnetic field lines of a
    current loop form closed curves that thread through the loop
    and return outside. In the meridional plane, the field lines
    are the contours of the flux function (Stokes stream function).

    This plot shows the characteristic dipole-like field pattern
    near and far from the loop.

    Args:
        loop_radius: Loop radius (cm).
        current: Current (abamperes).
        resolution: Grid resolution.
        ax: Existing axes to plot on (optional).

    Returns:
        Tuple of (Figure, Axes).

    Reference:
        Part IV, Art. 486: Magnetic field lines of current loops.
    """
    require_matplotlib()

    rho = np.linspace(0.05, 3.0, resolution)
    z = np.linspace(-2.0, 2.0, resolution)
    Rho, Z = np.meshgrid(rho, z)

    # Approximate field line pattern using dipole + near-field correction
    # For a dipole at origin: stream function psi ~ r*sin^2(theta) / r^2
    r = np.sqrt(Rho**2 + Z**2)
    sin_theta = Rho / np.maximum(r, 0.01)

    # Dipole stream function
    psi = sin_theta**2 / np.maximum(r, 0.1)

    # Near-field enhancement near the loop
    loop_enhancement = np.exp(-((Rho - loop_radius)**2 + Z**2) / (0.3 * loop_radius)**2)
    psi = psi * (1.0 + 2.0 * loop_enhancement)

    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 6))
    else:
        fig = ax.figure

    # Field lines (contours of stream function)
    ax.contour(
        Rho, Z, psi,
        levels=20,
        colors="steelblue",
        linewidths=1.0,
        alpha=0.7,
    )

    # Current loop
    ax.plot([loop_radius, loop_radius], [0, 0], "ro", markersize=12,
           label="Current loop")
    ax.plot([-loop_radius, -loop_radius], [0, 0], "ro", markersize=12)

    # Axis of symmetry
    ax.axhline(y=0, color="gray", linestyle="--", linewidth=0.5, alpha=0.3)
    ax.axvline(x=0, color="gray", linestyle="--", linewidth=0.5, alpha=0.3)

    ax.set_xlabel(r"Cylindrical radius $\rho$ (cm)")
    ax.set_ylabel("z (cm)")
    ax.set_title("Magnetic Field Lines of Current Loop (Art. 486)")
    ax.legend(loc="best", fontsize=9)
    ax.set_aspect("equal")

    fig.tight_layout()
    return fig, ax
