"""Wave-9 REQ-V battery: reference-store integrity + cross-checks (Arts 667-866).

This battery guards the Wave-9 expansion of
``tests/articles/reference_values.json`` from 71 to 200 in-scope articles:

1. **Integrity** -- schema validation, 200/200 in-scope coverage,
   finiteness, tolerance shape (belt-and-braces on top of
   ``validate_store``).
2. **Provenance discipline** -- every builder-generated entry must carry a
   provenance class marker (Class 2..5) and must never cite the maxwell
   package's own output as the value's origin.
3. **Internal consistency** -- independently-derived pins must agree with
   each other (694 kernel reconstructed from the 703/704 pins; 703 K-pin
   vs the 705 AGM-pin through K = pi/(2 AGM)).
4. **External cross-checks** -- elliptic pins vs scipy (third party), and a
   probed subset where store pins are compared against modules computing
   the same quantity (ESU/EMU unit ratio, plane-wave wavelength and the
   Gaussian E/B relation).

The store pins were derived *independently* of the maxwell package by
``scripts/build_reference_store_wave9.py``; agreement between a module and
a pin is therefore evidence that both capture the same physics, not
self-confirmation.
"""

from __future__ import annotations

import math

import numpy as np
import pytest

from articles import (
    entry,
    reference_values,
    ref_value,
    tolerance_of,
    validate_store,
)

BUILDER_TAG = "build_reference_store_wave9.py"
IN_SCOPE = range(667, 867)
CLASS_MARKERS = ("Class 2", "Class 3", "Class 4", "Class 5")


def _builder_entries():
    """Yield (article, key, val) for every entry generated by the Wave-9 builder."""
    for art, art_entry in reference_values().items():
        for key, val in art_entry.get("values", {}).items():
            if BUILDER_TAG in val.get("provenance", ""):
                yield art, key, val


class TestStoreIntegrityWave9:
    """Schema and coverage integrity of the expanded store."""

    def test_validate_store_clean(self):
        assert validate_store() == []

    def test_all_200_in_scope_articles_present(self):
        store = reference_values()
        missing = [a for a in IN_SCOPE if str(a) not in store]
        assert missing == []

    def test_in_scope_coverage_count_is_200(self):
        covered = sum(1 for a in IN_SCOPE if str(a) in reference_values())
        assert covered == 200

    def test_every_in_scope_article_has_at_least_one_value(self):
        empty = [a for a in IN_SCOPE if not entry(a).get("values")]
        assert empty == []

    def test_in_scope_values_all_finite(self):
        bad = [
            (a, k)
            for a in IN_SCOPE
            for k, v in entry(a)["values"].items()
            if not math.isfinite(v["value"])
        ]
        assert bad == []

    def test_wave9_builder_added_exactly_129_articles(self):
        # Historical regression pin for the Wave-9 expansion (71 -> 200).
        arts = {art for art, _, _ in _builder_entries()}
        assert len(arts) == 129


class TestProvenanceDiscipline:
    """Anti-theater checks on builder-generated provenance."""

    def test_builder_entries_carry_class_markers(self):
        unmarked = [
            (art, key)
            for art, key, val in _builder_entries()
            if not any(marker in val["provenance"] for marker in CLASS_MARKERS)
        ]
        assert unmarked == []

    def test_builder_entries_never_cite_module_output(self):
        forbidden = (
            "computed by maxwell",
            "computed by the maxwell",
            "module output",
            "taken from maxwell",
            "output of the module",
            "matches module",
        )
        offenders = [
            (art, key)
            for art, key, val in _builder_entries()
            if any(phrase in val["provenance"].lower() for phrase in forbidden)
        ]
        assert offenders == []

    def test_builder_entries_tolerance_shape(self):
        for art, key, val in _builder_entries():
            assert set(val["tolerance"]) in ({"rel"}, {"abs"}), (art, key)
            (bound,) = val["tolerance"].values()
            assert isinstance(bound, (int, float)) and bound >= 0, (art, key)
            value = val["value"]
            assert isinstance(value, (int, float)) and not isinstance(value, bool), (
                art,
                key,
            )


class TestInternalPinConsistency:
    """Independently-derived pins must be mutually consistent."""

    def test_694_kernel_reconstructs_from_703_704_pins(self):
        kernel = ref_value(694, "Aphi_kernel_at_m_half")
        K = ref_value(703, "K_at_m_half_AGM")
        E = ref_value(704, "E_at_m_half_series")
        assert kernel == pytest.approx(1.5 * K - 2.0 * E, rel=1e-13)

    def test_703_K_pin_vs_705_AGM_pin(self):
        # K(1/2) = pi / (2 AGM(1, sqrt(1/2))): two independent pins, one law.
        K = ref_value(703, "K_at_m_half_AGM")
        M = ref_value(705, "AGM_fixed_point_1_sqrt_half")
        assert K == pytest.approx(math.pi / (2.0 * M), rel=1e-12)


class TestExternalCrossChecks:
    """Store pins vs third-party values and module computations."""

    def test_K_half_vs_scipy(self):
        from scipy.special import ellipk

        assert ellipk(0.5) == pytest.approx(
            ref_value(703, "K_at_m_half_AGM"),
            **tolerance_of(703, "K_at_m_half_AGM"),
        )

    def test_E_half_vs_scipy(self):
        from scipy.special import ellipe

        assert ellipe(0.5) == pytest.approx(
            ref_value(704, "E_at_m_half_series"),
            **tolerance_of(704, "E_at_m_half_series"),
        )

    def test_esu_emu_ratio_module_matches_store(self):
        # Store pin (769): (ESU/EMU charge ratio)/c = 1, independently derived.
        # Module side: the CGS converter's EMU->ESU charge factor must be c.
        from maxwell.config.constants import C
        from maxwell.core.units.units import CGSUnitConverter

        ratio = CGSUnitConverter().emu_to_esu_charge(1.0) / C
        assert ratio == pytest.approx(
            ref_value(769, "unit_ratio_over_c"),
            **tolerance_of(769, "unit_ratio_over_c"),
        )

    def test_plane_wave_lambda_module_matches_store(self):
        # Store pin (787): lambda = c/f at f = 1e14 Hz, independently derived.
        # Module side: PlaneWave must preserve |k| = omega/c so 2 pi/|k| = c/f.
        from maxwell.config.constants import C
        from maxwell.optics.wave_equation import PlaneWave

        E0 = np.array([1.0, 0.0, 0.0])
        omega = 2.0 * math.pi * 1.0e14
        k = np.array([0.0, 0.0, omega / C])
        pw = PlaneWave(E0=E0, k=k, omega=omega)
        lam = 2.0 * math.pi / np.linalg.norm(pw.k)
        assert lam == pytest.approx(
            ref_value(787, "lambda_c_over_f_1e14"),
            **tolerance_of(787, "lambda_c_over_f_1e14"),
        )

    def test_plane_wave_E_over_B_module_matches_store(self):
        # Store pin (781): (E/B)/c = 1 for a vacuum Gaussian plane wave,
        # independently pinned. Module side: PlaneWave.evaluate derives
        # B = (1/omega) k x E, so with |k| = omega/c the ratio must be c.
        from maxwell.config.constants import C
        from maxwell.optics.wave_equation import PlaneWave

        E0 = np.array([1.0, 0.0, 0.0])
        omega = 2.0 * math.pi * 1.0e14
        k = np.array([0.0, 0.0, omega / C])
        pw = PlaneWave(E0=E0, k=k, omega=omega)
        E_field, B_field = pw.evaluate(np.zeros(3), 0.0)
        ratio = (np.linalg.norm(E_field) / np.linalg.norm(B_field)) / C
        assert ratio == pytest.approx(
            ref_value(781, "E_over_B_is_c"),
            **tolerance_of(781, "E_over_B_is_c"),
        )
